
-- Insert Mentor subscription plan
INSERT INTO public.subscription_plans (name, price_usd, price_zar, trading_accounts_limit, copy_accounts_limit, auto_trades_limit, ai_bots_enabled, custom_risk_enabled, priority_support, features)
VALUES ('mentor', 55, 999, 20, 20, 500, true, true, true, '["Everything in Enterprise", "White-label branding", "Custom feature naming", "Referral system & tracking", "Client management dashboard", "Share trading ideas to clients", "Copy trading for clients", "AI Bot for clients", "Dedicated mentor support"]'::jsonb)
ON CONFLICT (name) DO NOTHING;

-- Seed training content
INSERT INTO public.training_content (title, description, type, url, difficulty, tags, category, order_index, content_text) VALUES
('What is Forex Trading?', 'Introduction to the foreign exchange market and how currency pairs work.', 'lesson', 'https://www.babypips.com/learn/forex/what-is-forex', 'beginner', ARRAY['forex','basics','introduction'], 'Forex Basics', 1, 'Forex (FX) is the marketplace where currencies are traded. The forex market is the largest, most liquid market in the world, with trillions of dollars changing hands every day.'),
('Understanding Currency Pairs', 'Learn about major, minor, and exotic currency pairs.', 'lesson', 'https://www.babypips.com/learn/forex/know-your-currency-pairs', 'beginner', ARRAY['forex','currency pairs','basics'], 'Forex Basics', 2, 'Currency pairs compare the value of one currency to another. The first currency is the base currency, and the second is the quote currency.'),
('How to Read Candlestick Charts', 'Master the art of reading Japanese candlestick patterns.', 'lesson', NULL, 'beginner', ARRAY['charts','candlesticks','technical analysis'], 'Technical Analysis', 3, 'Japanese candlestick charts display the high, low, open, and close prices for a security during a specific period. Each candlestick represents one period of data.'),
('Support and Resistance Levels', 'Understanding key price levels where buying and selling pressure meet.', 'lesson', NULL, 'beginner', ARRAY['support','resistance','technical analysis'], 'Technical Analysis', 4, 'Support is a price level where a downtrend can be expected to pause. Resistance is a price level where an uptrend can be expected to pause.'),
('Risk Management Fundamentals', 'Learn how to protect your capital with proper risk management.', 'lesson', NULL, 'beginner', ARRAY['risk management','money management','basics'], 'Risk Management', 5, 'Never risk more than 1-2% of your account on a single trade. Use stop-loss orders to limit potential losses.'),
('Fibonacci Retracements', 'Using Fibonacci levels to identify potential reversal points.', 'lesson', NULL, 'intermediate', ARRAY['fibonacci','technical analysis','retracements'], 'Technical Analysis', 6, 'Fibonacci retracement levels are horizontal lines that indicate where support and resistance are likely to occur. They are based on Fibonacci numbers.'),
('Supply and Demand Trading', 'Identify institutional order flow zones for high-probability trades.', 'lesson', NULL, 'intermediate', ARRAY['supply demand','institutional','zones'], 'Price Action', 7, 'Supply and demand zones represent areas where institutional traders have placed large orders. These zones often act as strong support and resistance.'),
('ICT Concepts - Market Structure', 'Inner Circle Trader methodology for understanding market structure.', 'lesson', NULL, 'intermediate', ARRAY['ICT','market structure','smart money'], 'Smart Money Concepts', 8, 'Market structure is the foundation of ICT trading. It involves identifying higher highs, higher lows (bullish) and lower highs, lower lows (bearish).'),
('Fair Value Gaps (FVG)', 'Understanding and trading Fair Value Gaps in price action.', 'lesson', NULL, 'advanced', ARRAY['FVG','fair value gap','ICT','smart money'], 'Smart Money Concepts', 9, 'A Fair Value Gap is a three-candle pattern where the wicks of the first and third candle do not overlap, creating an imbalance in price.'),
('Beat The Market Maker - Steve Mauro', 'Learn the Market Maker strategy by Steve Mauro for understanding institutional manipulation.', 'lesson', NULL, 'advanced', ARRAY['market maker','Steve Mauro','manipulation','institutional'], 'Advanced Strategies', 10, 'Steve Mauro''s Beat The Market Maker strategy teaches traders to identify how market makers manipulate price to trigger retail stop-losses before moving in the intended direction.'),
('Order Blocks and Breaker Blocks', 'Identifying institutional order blocks for precision entries.', 'lesson', NULL, 'advanced', ARRAY['order blocks','breaker blocks','ICT','smart money'], 'Smart Money Concepts', 11, 'Order blocks are the last opposing candle before a strong move. They represent areas where institutions have placed orders and price is likely to return.'),
('Algorithmic Trading Basics', 'Introduction to automated trading systems and expert advisors.', 'lesson', NULL, 'advanced', ARRAY['algorithmic','automated','EA','expert advisor'], 'Algorithmic Trading', 12, 'Algorithmic trading uses computer programs to execute trades based on predefined rules. This removes emotional bias and allows 24/7 trading.'),
('Forex Trading for Beginners - Full Course', 'Complete forex trading course covering all the basics.', 'video', 'https://www.youtube.com/watch?v=rA0RmFYFiC4', 'beginner', ARRAY['forex','beginners','course'], 'Forex Basics', 13, NULL),
('ICT Mentorship 2022 - Core Content', 'Inner Circle Trader complete mentorship series.', 'video', 'https://www.youtube.com/watch?v=QRUfMnVvWJg', 'advanced', ARRAY['ICT','mentorship','smart money'], 'Smart Money Concepts', 14, NULL),
('Supply and Demand Trading Strategy', 'Comprehensive guide to supply and demand zone trading.', 'video', 'https://www.youtube.com/watch?v=TJQlGEon2Jk', 'intermediate', ARRAY['supply demand','strategy'], 'Price Action', 15, NULL),
('Trading in the Zone - Mark Douglas', 'A must-read book on trading psychology and discipline.', 'book', 'https://www.amazon.com/Trading-Zone-Confidence-Discipline-Attitude/dp/0735201447', 'beginner', ARRAY['psychology','discipline','mindset'], 'Trading Psychology', 16, NULL),
('Japanese Candlestick Charting Techniques - Steve Nison', 'The definitive guide to candlestick charting.', 'book', 'https://www.amazon.com/Japanese-Candlestick-Charting-Techniques-Contemporary/dp/0735201811', 'intermediate', ARRAY['candlesticks','charting','technical analysis'], 'Technical Analysis', 17, NULL),
('Technical Analysis Cheat Sheet', 'Quick reference guide for common chart patterns and indicators.', 'pdf', NULL, 'beginner', ARRAY['cheat sheet','patterns','indicators'], 'Technical Analysis', 18, NULL),
('Risk Management Calculator Guide', 'Step-by-step guide for calculating position sizes and risk.', 'pdf', NULL, 'beginner', ARRAY['risk management','position sizing','calculator'], 'Risk Management', 19, NULL),
('TradingView', 'Professional charting platform with social trading features.', 'tool', 'https://www.tradingview.com', 'beginner', ARRAY['charting','tools','platform'], 'Trading Tools', 20, NULL);
